/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HealthRouteImport } from './routes/health'
import { Route as WatchLoginRouteImport } from './routes/watch.$login'
import { Route as WatchMultiviewRouteImport } from './routes/watch.multiview'
import { Route as ApiPublicHealthCheckRouteImport } from './routes/api/public/health-check'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLoginRoute = WatchLoginRouteImport.update({
  id: '/watch/$login',
  path: '/watch/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMultiviewRoute = WatchMultiviewRouteImport.update({
  id: '/watch/multiview',
  path: '/watch/multiview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthCheckRoute = ApiPublicHealthCheckRouteImport.update({
  id: '/api/public/health-check',
  path: '/api/public/health-check',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/watch/$login': typeof WatchLoginRoute
  '/watch/multiview': typeof WatchMultiviewRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/watch/$login': typeof WatchLoginRoute
  '/watch/multiview': typeof WatchMultiviewRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/watch/$login': typeof WatchLoginRoute
  '/watch/multiview': typeof WatchMultiviewRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/watch/$login'
    | '/watch/multiview'
    | '/api/public/health-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/watch/$login'
    | '/watch/multiview'
    | '/api/public/health-check'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/watch/$login'
    | '/watch/multiview'
    | '/api/public/health-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  WatchLoginRoute: typeof WatchLoginRoute
  WatchMultiviewRoute: typeof WatchMultiviewRoute
  ApiPublicHealthCheckRoute: typeof ApiPublicHealthCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$login': {
      id: '/watch/$login'
      path: '/watch/$login'
      fullPath: '/watch/$login'
      preLoaderRoute: typeof WatchLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/multiview': {
      id: '/watch/multiview'
      path: '/watch/multiview'
      fullPath: '/watch/multiview'
      preLoaderRoute: typeof WatchMultiviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-check': {
      id: '/api/public/health-check'
      path: '/api/public/health-check'
      fullPath: '/api/public/health-check'
      preLoaderRoute: typeof ApiPublicHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  WatchLoginRoute: WatchLoginRoute,
  WatchMultiviewRoute: WatchMultiviewRoute,
  ApiPublicHealthCheckRoute: ApiPublicHealthCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
