/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchLoginRouteImport } from './routes/watch.$login'
import { Route as WatchMultiviewRouteImport } from './routes/watch.multiview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchLoginRoute = WatchLoginRouteImport.update({
  id: '/watch/$login',
  path: '/watch/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchMultiviewRoute = WatchMultiviewRouteImport.update({
  id: '/watch/multiview',
  path: '/watch/multiview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/watch/$login': typeof WatchLoginRoute
  '/watch/multiview': typeof WatchMultiviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/watch/$login': typeof WatchLoginRoute
  '/watch/multiview': typeof WatchMultiviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/watch/$login': typeof WatchLoginRoute
  '/watch/multiview': typeof WatchMultiviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/watch/$login' | '/watch/multiview'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/watch/$login' | '/watch/multiview'
  id: '__root__' | '/' | '/watch/$login' | '/watch/multiview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WatchLoginRoute: typeof WatchLoginRoute
  WatchMultiviewRoute: typeof WatchMultiviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$login': {
      id: '/watch/$login'
      path: '/watch/$login'
      fullPath: '/watch/$login'
      preLoaderRoute: typeof WatchLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/multiview': {
      id: '/watch/multiview'
      path: '/watch/multiview'
      fullPath: '/watch/multiview'
      preLoaderRoute: typeof WatchMultiviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WatchLoginRoute: WatchLoginRoute,
  WatchMultiviewRoute: WatchMultiviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
